version: '2'
services:
  node-app:
    build: .
    ports:
     - "8080:8080"
    networks:
     - redis
    depends_on:
     - redis
  redis:
    image: redis
    ports:
     - "6379:6379"
    networks:
     - redis

networks:
  redis:
    driver: bridge